id: P000108
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཐེག་པ་ཆེན་པོ་ཞེན་པ་བཞི་བྲལ་གྱི་སྒོམ་ཁྲིད། །
  authors:
  - མཛད་པ་པོ། མཁན་ཆེན་ཨ་པད་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  id: IBA-MT-02-1
web_metadata:
  title:
    en: A Mahayana Meditation Instruction Based on Parting from the Four Attachments
    bo: ཐེག་པ་ཆེན་པོ་ཞེན་པ་བཞི་བྲལ་གྱི་སྒོམ་ཁྲིད།
  collection:
    en: IBA Mind Training Series–  Book 2
    bo: རྒྱལ་ཡོངས་གསུང་རབ་བློ་སྦྱོང་བསྟར་རིམ།–  དེབ། ༢
  author:
    en: Khenchen Appey Rinpoche
    bo: མཁན་ཆེན་ཨ་པད་རིན་པོ་ཆེ།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-MT-02-1
  category:
    en: Mind Training
    bo: བློ་སྦྱོང།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-MT-02-1.epub
  description:
    en: This text is practically beneficial for those who seek less chaotic life because
      in this text Rinpoche masterfully explain the causes of suffering and its remedies.
      It was taught during the summer in IBA.
    bo: ཐེག་པ་ཆེན་པོ་ཞེན་པ་བཞི་བྲལ་གྱི་སྒོམ་ཁྲིད། དེང་གི་དུས་སུ་ཉེ་བར་མཁོ་ཆེ་བའི་ཐེག་ཆེན་གྱི་ལམ་གྱི་རིམ་པ་མཐའ་དག་བསྡུས་ཏེ་བསྟན་པ།
